apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: httpd
    name: webserver
    release: stable
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: web
        image: httpd:2
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: demovol
          mountPath: /data
        - name: config-vol
          mountPath: /etc/config
        - name: secret-vol
          mountPath: /etc/secret
        - name: pv-vol
          mountPath: /etc/pvc
      volumes:
        - name: demovol
          hostPath:
            path: /data
            type: Directory
        - name: config-vol
          configMap:
            name: demo-config-map
        - name: secret-vol
          secret:
            secretName: demo-secrets
        - name: pv-vol
          persistentVolumeClaim:
            claimName: demo-pvc
 