apiVersion: v1
kind: Service
metadata:
  name: coupon-app
  labels:
    app: coupon-app
spec:
  selector:
    app: coupon-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
    nodePort: 30288