apiVersion: v1
kind: Service
metadata:
  name: product-app
  labels:
    app: product-app
spec:
  selector:
    app: product-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30289